# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20160408_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
