# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0003_policyapplication_is_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Identity', 'identity'), ('Employement Claim', 'employment-claim')], editable=False, max_length=32)),
                ('data', models.TextField(editable=False)),
                ('policy_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='policy.PolicyApplication')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('data', models.TextField()),
                ('result', models.CharField(max_length=32, null=True)),
                ('application_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='policy.ApplicationItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='peerreview',
            unique_together=set([('application_item', 'user')]),
        ),
    ]
