# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_riskassessmenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='rejected_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(3, 'on_p2p_review'), (8, 'active'), (6, 'on_smart_deposit_refund'), (2, 'submitted_wait_for_deposit'), (1, 'init'), (9, 'wait_for_premium'), (4, 'on_risk_assessment_review'), (7, 'deleted'), (5, 'approved')], default=1, protected=True),
        ),
    ]
