# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_riskassessmenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
