# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0010_applicationitem_is_finished'),
        ('policy', '0010_auto_20160915_2103'),
    ]

    operations = [
    ]
