# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-21 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmenttask',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment_tasks', to='policy.PolicyApplication'),
        ),
        migrations.AlterField(
            model_name='riskassessmenttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
