# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0012_auto_20160921_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='is_completeness_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(3, 'on_p2p_review'), (8, 'active'), (6, 'on_smart_deposit_refund'), (2, 'submitted_wait_for_deposit'), (1, 'init'), (9, 'wait_for_premium'), (4, 'on_risk_assessment_review'), (7, 'deleted'), (5, 'approved'), (10, 'on_completeness_check')], default=1, protected=True),
        ),
    ]
