# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_employmenthistoryjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistoryjob',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistoryjob',
            name='confirmer_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employmenthistoryjob',
            name='confirmer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistoryjob',
            name='job_titile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
