# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0017_auto_20161006_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyapplication',
            name='unemployment_period_answer',
            field=models.PositiveSmallIntegerField(choices=[(0, 'About 1 to 2 weeks'), (1, 'Maybe 3 weeks to 1 month'), (1, 'Perhaps 1 to 2 months'), (2, 'Possibly 2 to 3 months'), (3, 'Potentially 3 to 4 months'), (4, 'I will need more than 4 months of coverage.')], null=True),
        ),
    ]
