# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0018_auto_20161006_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyapplication',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(1, 'init'), (2, 'submitted'), (3, 'on_p2p_review'), (10, 'on_completeness_check'), (4, 'on_risk_assessment_review'), (5, 'approved'), (6, 'on_smart_deposit_refund'), (7, 'deleted'), (8, 'active'), (9, 'wait_for_premium')], default=1, protected=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='unemployment_period_answer',
            field=models.PositiveSmallIntegerField(choices=[(0, 'About 1 to 2 weeks'), (1, 'Maybe 3 weeks to 1 month'), (2, 'Perhaps 1 to 2 months'), (3, 'Possibly 2 to 3 months'), (4, 'Potentially 3 to 4 months'), (5, 'I will need more than 4 months of coverage.')], null=True),
        ),
    ]
