# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0019_auto_20161010_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmenttask',
            name='question1',
            field=models.PositiveSmallIntegerField(help_text='How many months will this policyholder pay in premiums before opening a claim?', null=True),
        ),
        migrations.AddField(
            model_name='riskassessmenttask',
            name='question2',
            field=models.FloatField(help_text='How many weeks will this policyholder recieve in payments before closing a claim? ', null=True),
        ),
    ]
