# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0020_auto_20161011_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtask',
            name='policy_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='policy.PolicyApplication'),
        ),
    ]
