ingFORMAT: 1A
HOST: http://dynamisapp.herokuapp.com/

# Dynamis Backend API

This is a Dynamis API description. 

## Login [/api/v1/login]

Log in user and get **sessionid** Cookie.

### Login [POST /api/v1/login]

+ Request (application/json)

        {
            "email": "sample@email.com",
            "password": "123456"
        }
        
+ Response 200
    + Headers
    
            Cookies: sessionid
    + Body
    
                {
                    // current user account ID
                    "accountid": "123456"
                }

## Logout [/api/v1/logout]

Log the user out

### Logout [POST /api/v1/logout]

+ Request
    
    + Body
    
            {
            }
    
+ Response 200


## Accounts [/api/v1/accounts/{accountid}]

### Create new Account [POST /api/v1/accounts]

TODO: this method is not implemented yet

Create new account by calling this method. As a side-effect will send user a verification e-mail.

+ Request (application/json)

        {
            "email": "sample@email.com",
            "password1": "123456",
            "password2": "123456",
            
            // the field is optional
            "linkedin_account": "http://me.linkedin.com",
            
            // TODO: still not implemented
            // the field is optional
            "keybase_username": "someusername",
            
            // TODO: still not implemented
            // the field is optional
            "eth_address": "0xCf14744B3B4Ac720026569249CA4eb19Fc86A708"
        }
        
+ Response 200

### Get all Accounts [GET /api/v1/accounts]

Get list of all account IDs. 

+ Response 200
    + Body

            {
                "results": 
                [
                    "231313231",
                    "231421843",
                    "894898989"
                ]
            }

### Update Account [PUT /api/v1/accounts/{accountid}]

Change account parameters (email, keybase_username)

If **admin** - can update any account info. 

If **not admin** - can update only my account info.

+ Parameters
    + accountid (number) - ID of an account

+ Response 200 (application/json)

    + Body

            {
                "email": "xxx@mail.com",
                "keybase_username": "something",
                
                "linkedin_account": "http://me.linkedin.com",
            
                // only if admin is asking:
                "email_verified": true,
                "active": true,
                "superuser": true,
                "staff": true,
                "risk_assessor": true,
                
                // these can't be set
                // "date_joined": "",
                // "last_login": ""
            }

### Get Account [GET /api/v1/accounts/{accountid}]

Get account data.

If **admin** - can get any account info. 

If **not admin** - can get only my account info.

+ Parameters
    + accountid (number) - ID of an account

+ Response 200 (application/json)

    + Body

            {
                "email": "xxx@mail.com",
                "keybase_username": "something",
                "eth_address": "0xCf14744B3B4Ac720026569249CA4eb19Fc86A708",
                
                "linkedin_account": "http://me.linkedin.com",

                "is_keybase_verified": true,
                
                // only if admin is asking:
                "email_verified": true,
                "keybase_username": "",
                "active": true,
                "superuser": true,
                "staff": true,
                "risk_assessor": true,
                "date_joined": "",
                "last_login": ""
            }
            
### Update Settings [PUT /api/v1/accounts/{accountid}/settings]

The settings is some params that user has set. For example: view color or list sort type. 

If **admin** - can update any account settings. 

If **not admin** - can update only my account settings.

+ Parameters
    + accountid (number) - ID of an account

+ Request (application/json)

        {
            "eth_node_host": "http://52.16.72.86:8545",
        }
        
+ Response 200

### Get Settings [GET /api/v1/accounts/{accountid}/settings]

The settings is some params that user has set. For example: view color or list sort type. 

If **admin** - can get any account settings. 

If **not admin** - can get only my account settings.

+ Parameters
    + accountid (number) - ID of an account
    
+ Response 200

            {
                "eth_node_host": "http://52.16.72.86:8545"
            }         

### Verify Keybase [PUT /api/v1/accounts/{accountid}/keybase]

Validate the user's keybase account. signed_message must be signed by user. We will check that it is signed with account's keybase key. 
That is to make sure that valid keybase account is connected with current Dynamis user. 

If signature is bad - return 404.

+ Parameters
    + accountid (number) - ID of an account
    
+ Request (application/json)

        {
            "signed_message": "123123123123cxxfsq24390dXFasdfj234",
            "keybase_username": "tonykent"
        }
        
+ Response 200

+ Response 400

## Peer Review Tasks [/api/v1/review-tasks]

### Get Items for Peer Review [GET]

TODO: this method is not implemented yet.

Get list of items that need to be reviewed (by me). This is not a **risk assessment tasks** (that is done only by RiskAssessors)! 
Before we need to verify user identity and verify employment information. This is done by an ordinary users. 

If **admin** - get all tasks for all users. 
If **not admin** - get all tasks for current user (me) only.

+ Response 200
    + Body
    
            {
                tasks: [
                    {
                        // global review task ID
                        id: 1,
            
                        // TODO: is reviewed?
                        is_finished: true
                    },
                    ...
                ]
            }


### Get Item for Peer Review [GET /api/v1/review-tasks/{review_task_id}]

TODO: this method is not implemented yet.

Get Peer Review task.

+ Parameters
    + review_task_id (number) - ID of a task
    
+ Response 200
    + Body
    
            {
                "type": "employment-claim",
                "files": [],
                "startYear": "2012",
                "company": "Some Company",
                "startMonth": "4",
                "currentJob": true,
                "endMonth": 7,
                "state": "READ_ONLY",
                "endYear": 2016,
                "notes": "* Job Title:\n* ..."
            }

### Submit Peer Review [POST /api/v1/review-tasks/{review_task_id}/verify]

TODO: this method is not implemented yet.

After the Peer has reviewed some parts of an application - i want to be able to set **Verify/Falsify/Can't Tell**. 

Please see [screenshot here](https://s4.postimg.org/47engihul/Screen_Shot_2016_08_17_at_19_05_14.png).

Please see [another screenshot here](https://s3.postimg.org/a501ucv83/Screen_Shot_2016_08_17_at_19_07_10.png).

That creates the message ```{"task_hash":"things","result":"no"}``` (for example) that he needs then to sign.

+ Parameters
    + review_task_id (number) - ID of a task

+ Request (application/json)
    + Body

            {
                "signed_message": "4234234jkfjsdlkfaj"
            }
        
+ Response 200

## Assessment Tasks [/api/v1/assessment_tasks]

### Get List of My Assessment Tasks [GET /api/v1/assessment_tasks]

Assessment Task is a 'task' that is assigned to RiskAssessor. RiskAssessor should review it and make a bet.

RiskAssessor wants to get list of assessments that is assigned to him.

If **admin** - get all tasks for all users. 
If **not admin** - get all tasks for current user (me) only.

+ Response 200 (application/json)
    
        {
            tasks: [
                {
                    // global assessment ID
                    id: 1,
                    
                    // is RiskAssessor finished to review it?
                    is_finished: true
                },
                ...
            ]
        }

 
### Get Assessment Tasks Info [GET /api/v1/assessment_tasks/{taskid}]

Get assessment full info.
If **admin** - can get any.
If **not admin** - can get only my assessments.

+ Parameters
    + taskid (number) - Assessment Task ID (global for all users)

+ Response 200 (application/json)
    
        {
            // linked with policies (global ID)
            policyid: 123,
            
            // is RiskAssessor finished to review it?
            is_finished: true
                    
            bet1: 1.2,
            bet2: 2.2
        }
   
### Update Assessment Task Info [PUT /api/v1/assessment_tasks/{taskid}]


Update assessment task data.
If **admin** - can get any.
If **not admin** - can get only my assessment tasks.

+ Parameters
    + taskid (number) - Assessment Task ID (global for all users)

+ Request (application/json)
    
        {
            // is RiskAssessor finished to review it?
            is_finished: true
                    
            bet1: 1.2,
          
            bet2: 2.2
        }

+ Response 200

## Policies [/api/v1/policies/{policyid}]

### Create new Policy [POST /api/v1/policies]

Create empty policy for **userid**.

+ Request
    + Body
    
            {
            }
            
+ Response 200

### Get all Policies list [GET /api/v1/policies]

Get list of all policy IDs. 

If **admin** - get all policies for all users.
If **not admin** - get all policies for current user (me) only.

+ Response 200
    + Body

            {
                "results": 
                [
                    "1",
                    "3",
                    "4"
                ]
            }

### Get Policy [GET /api/v1/policies/{policyid}]

Get the policy data.

In insurance, the insurance **policy** is a contract (generally a standard form contract) between the insurer and the insured, known as the policyholder, which determines the claims which the insurer is legally required to pay. In exchange for an initial payment, known as the premium, the insurer promises to pay for loss caused by perils covered under the policy language.

Insurance contracts are designed to meet specific needs and thus have many features not found in many other types of contracts. Since insurance policies are standard forms, they feature boilerplate language which is similar across a wide variety of different types of insurance policies.

+ Parameters
    + policyid (number) - ID of a policy (global for all users)

+ Response 200 (application/json)
    
        {
            "id": 1,
            
            // TODO: field is still not implemented
            "is_signed": true,
                
            "data":
            {
                "public_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: KEY BLOCK-----",
                "signed_message": "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\n{\"identity\":{\"verification_method\":\"keybase\",\"verificati`-----END PGP SIGNATURE-----",
                "public_key_identity": {
                    "username": "tonykent"
                },
                "public_key_provider": "keybase",
                "policy_data": {
                    "requestedPremiumAmount": "46",
                    "identity": {
                        "verification_method": "keybase",
                        "verification_data": {
                            "username": "tonykent",
                            "proofs": [
                                {
                                    "proof_id": "6bd6da447e3d1b0b4a17c210",
                                    "proof_url": "https://twitter.com/anthonyakentiev/status/763656278963085312",
                                    "presentation_tag": "tweet",
                                    "nametag": "anthonyakentiev",
                                    "human_url": "https://twitter.com/anthonyakentiev/status/763656278963085312",
                                    "state": 1,
                                    "proof_type": "twitter",
                                    "service_url": "https://twitter.com/anthonyakentiev",
                                    "sig_id": "476015a934a9b5878b7572ad49853e77e331c36eec76dd836bb78cd45ff3e8d90f",
                                    "presentation_group": "twitter"
                                },
                                {
                                    "proof_id": "e26f23f128e6f92ed7955910",
                                    "proof_url": "https://gist.github.com/49e0adf02231361735edd4937d43dc56",
                                    "presentation_tag": "gist",
                                    "nametag": "anthonyakentiev",
                                    "human_url": "https://gist.github.com/49e0adf02231361735edd4937d43dc56",
                                    "state": 1,
                                    "proof_type": "github",
                                    "service_url": "https://github.com/anthonyakentiev",
                                    "sig_id": "5e82869934b8693128f8f4f3023467a9ba7529fc509ae35b364d297ff9982c0c0f",
                                    "presentation_group": "github"
                                }
                            ]
                        }
                    },
                    "employmentHistory": {
                        "jobs": [
                            {
                                "files": [],
                                "startYear": "2012",
                                "company": "Sample",
                                "startMonth": "6",
                                "currentJob": true,
                                "endMonth": 7,
                                "state": "READ_ONLY",
                                "endYear": 2016,
                                "notes": "* Job Title:\n* Reason for leaving:\nProgrammer."
                            }
                        ]
                    }
                }
            }
        }
        
 
### Update Policy [PUT /api/v1/policies/{policyid}]

Update the policy.

+ Request (application/json)
    + Body

            {
                "data": 
                {
                    "identity": {
                        "verification_method": "keybase",
                        "verification_data": {}
                    },
                    "employmentHistory": {
                        "jobs": [
                            {
                                "files": [],
                                "state": "READ_ONLY",
                                "notes": "* Job Title:\n* ....",
                                "currentJob": true,
                                "startMonth": "3",
                                "endMonth": 7,
                                "endYear": 2016,
                                "startYear": "2015"
                            }
                        ]
                    },
                    "requestedPremiumAmount": 250
                }
            }
        
+ Response 200 (application/json)
    + Body
    
            {
                "id": 1, 
                "data": {
                    "requestedPremiumAmount": 250,
                    "identity": {
                        "verification_method": "keybase",
                        "verification_data": {}
                    },
                    "employmentHistory": {
                        "jobs": [
                            {
                                "files": [],
                                "startYear": "2015",
                                "notes": "* Job Title:\n* ....",
                                "startMonth": "3",
                                "currentJob": true,
                                "endMonth": 7,
                                "state": "READ_ONLY",
                                "endYear": 2016
                            }
                        ]
                    }
                }
            }

### Sign a Policy [POST /api/v1/policies/{policyid}/signature]

After all data is entered - user can submit a policy application. The peers will then review it. 

If signature is bad -> return 404.

+ Request (application/json)
    + Body

            {
                "keybase_username": "tonykent",
                "signed_message": "fjdskajflakjdfkweu2434"
            }
        
+ Response 200


### Upload File to Policy [POST /api/v1/policies/{policyid}/file]

Attach the file to the application. Will uplad it to IPFS.

+ Request (application/json)
    + Body

            {
                "filename": "file1.png",
                "data_url": "data:image/png;base64,iVBORw0KGgoAAAANS...",
                "mimetype": "image/png"
            }
        
+ Response 200







## DEPRECATED: Create new Account [/api/v1/accounts/account-create]

### Create new Account [POST]

WARNING: this is DEPRECETATED method and will be removed soon!

Create new account by calling this method. As a side-effect will send user a verification e-mail.

+ Request (application/json)

        {
            "email": "sample@email.com",
            "password1": "123456",
            "password2": "123456"
        }
        
+ Response 200

## DEPRECATED: Verify Keybase Account [/api/v1/accounts/verify-keybase]

### Verify Keybase [POST]

WARNING: this is DEPRECETATED method and will be removed soon!

Validate the user's keybase account. signed_message must be signed by user. We will check that it is signed with account's keybase key. 
That is to make sure that valid keybase account is connected with current Dynamis user. 

+ Request (application/json)

        {
            "signed_message": "123123123123cxxfsq24390dXFasdfj234",
            "keybase_username": "tonykent"
        }
        
+ Response 200



## DEPRECATED: Policies [/api/v1/application/policies/{policyid}/]

### Get Policy [GET]

Get the policy data.

In insurance, the insurance **policy** is a contract (generally a standard form contract) between the insurer and the insured, known as the policyholder, which determines the claims which the insurer is legally required to pay. In exchange for an initial payment, known as the premium, the insurer promises to pay for loss caused by perils covered under the policy language.

Insurance contracts are designed to meet specific needs and thus have many features not found in many other types of contracts. Since insurance policies are standard forms, they feature boilerplate language which is similar across a wide variety of different types of insurance policies.

+ Parameters
    + policyid (number) - ID of a policy (global for all users)

+ Response 200 (application/json)
    
        {
            "id": 1,
            "data":
            {
                "public_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: KEY BLOCK-----",
                "signed_message": "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA512\n\n{\"identity\":{\"verification_method\":\"keybase\",\"verificati`-----END PGP SIGNATURE-----",
                "public_key_identity": {
                    "username": "tonykent"
                },
                "public_key_provider": "keybase",
                "policy_data": {
                    "requestedPremiumAmount": "46",
                    "identity": {
                        "verification_method": "keybase",
                        "verification_data": {
                            "username": "tonykent",
                            "proofs": [
                                {
                                    "proof_id": "6bd6da447e3d1b0b4a17c210",
                                    "proof_url": "https://twitter.com/anthonyakentiev/status/763656278963085312",
                                    "presentation_tag": "tweet",
                                    "nametag": "anthonyakentiev",
                                    "human_url": "https://twitter.com/anthonyakentiev/status/763656278963085312",
                                    "state": 1,
                                    "proof_type": "twitter",
                                    "service_url": "https://twitter.com/anthonyakentiev",
                                    "sig_id": "476015a934a9b5878b7572ad49853e77e331c36eec76dd836bb78cd45ff3e8d90f",
                                    "presentation_group": "twitter"
                                },
                                {
                                    "proof_id": "e26f23f128e6f92ed7955910",
                                    "proof_url": "https://gist.github.com/49e0adf02231361735edd4937d43dc56",
                                    "presentation_tag": "gist",
                                    "nametag": "anthonyakentiev",
                                    "human_url": "https://gist.github.com/49e0adf02231361735edd4937d43dc56",
                                    "state": 1,
                                    "proof_type": "github",
                                    "service_url": "https://github.com/anthonyakentiev",
                                    "sig_id": "5e82869934b8693128f8f4f3023467a9ba7529fc509ae35b364d297ff9982c0c0f",
                                    "presentation_group": "github"
                                }
                            ]
                        }
                    },
                    "employmentHistory": {
                        "jobs": [
                            {
                                "files": [],
                                "startYear": "2012",
                                "company": "Sample",
                                "startMonth": "6",
                                "currentJob": true,
                                "endMonth": 7,
                                "state": "READ_ONLY",
                                "endYear": 2016,
                                "notes": "* Job Title:\n* Reason for leaving:\nProgrammer."
                            }
                        ]
                    }
                }
            }
        }
        
 
### Update Policy [PUT]

Update the policy.

+ Request (application/json)
    + Body

            {
                "data": 
                {
                    "identity": {
                        "verification_method": "keybase",
                        "verification_data": {}
                    },
                    "employmentHistory": {
                        "jobs": [
                            {
                                "files": [],
                                "state": "READ_ONLY",
                                "notes": "* Job Title:\n* ....",
                                "currentJob": true,
                                "startMonth": "3",
                                "endMonth": 7,
                                "endYear": 2016,
                                "startYear": "2015"
                            }
                        ]
                    },
                    "requestedPremiumAmount": 250
                }
            }
        
+ Response 200 (application/json)
    + Body
    
            {
                "id": 1, 
                "data": {
                    "requestedPremiumAmount": 250,
                    "identity": {
                        "verification_method": "keybase",
                        "verification_data": {}
                    },
                    "employmentHistory": {
                        "jobs": [
                            {
                                "files": [],
                                "startYear": "2015",
                                "notes": "* Job Title:\n* ....",
                                "startMonth": "3",
                                "currentJob": true,
                                "endMonth": 7,
                                "state": "READ_ONLY",
                                "endYear": 2016
                            }
                        ]
                    }
                }
            }

## DEPRECATED: Application [/api/v1/application/policies/{policyid}/submit]

### Submit a Policy Application [POST]

After all data is entered - user can submit a policy application. The peers will then review it. 

+ Request (application/json)
    + Body

            {
                "keybase_username": "tonykent",
                "signed_message": "fjdskajflakjdfkweu2434"
            }
        
+ Response 200


## DEPRECATED: Upload File [/api/v1/application/policies/{policyid}/upload-file]

### Upload File to Policy [POST]

Attach the file to the application. Will uplad it to IPFS.

+ Request (application/json)
    + Body

            {
                "filename": "file1.png",
                "data_url": "data:image/png;base64,iVBORw0KGgoAAAANS...",
                "mimetype": "image/png"
            }
        
+ Response 200

## DEPRECATED: Application Items [/api/v1/application/application-items]

### Get all Application Items [GET]

Get list of items that need to be reviewed (by you).

+ Response 200
    + Body
    
            {
                "count": 4, 
                "next": null, 
                "previous": null, 
                "results": [
                    {
                        "id": 4,
                        "type": "employment-claim",
                        "data": {
                            "files": [],
                            "startYear": "2012",
                            "company": "Some Company",
                            "startMonth": "4",
                            "currentJob": true,
                            "endMonth": 7,
                            "state": "READ_ONLY",
                            "endYear": 2016,
                            "notes": "* Job Title:\n* ..."
                        }
                    },
                    {
                        "id": 5,
                        "type": "identity",
                        "data": {
                            "proof_id": "82a65cae07098baf1bbc3010",
                            "proof_url": "https://twitter.com/joshuad31/status/715338474593714176",
                            "presentation_tag": "tweet",
                            "nametag": "joshuad31",
                            "human_url": "https://twitter.com/joshuad31/status/715338474593714176",
                            "state": 1,
                            "proof_type": "twitter",
                            "service_url": "https://twitter.com/joshuad31",
                            "sig_id": "4736793cfd5c53dc2991bd3d1e6c03f8228698aa5d83bb694e90cae358981aeb0f",
                            "presentation_group": "twitter"
                        }
                    },
                    {
                        "id": 6,
                        "type": "identity",
                        "data": {
                            "proof_id": "89c8fe08f77974ea6c2a4b10",
                            "proof_url": "https://keybase.io/joshuad31/sigchain#4f1c7845f623eaeecc9c143525b2aead1fe099ded23a1d24d18f58761d61e5660f",
                            "presentation_tag": "dns",
                            "nametag": "dynamisapp.com",
                            "human_url": "dns://dynamisapp.com",
                            "state": 1,
                            "proof_type": "dns",
                            "service_url": "http://dynamisapp.com",
                            "sig_id": "4f1c7845f623eaeecc9c143525b2aead1fe099ded23a1d24d18f58761d61e5660f",
                            "presentation_group": "dynamisapp.com"
                        }
                    },
                    {
                        "id": 7,
                        "type": "employment-claim",
                        "data": {
                            "files": [],
                            "startYear": "2012",
                            "company": "International Paper",
                            "startMonth": "0",
                            "currentJob": false,
                            "endMonth": "2",
                            "state": "READ_ONLY",
                            "endYear": "2016",
                            "notes": "* Job Title: Voice Engineer\n* Reason for leaving: Start working on Dynamis\n\nIn order to verify my employment at International paper you can contact Lisa Harmon who was my boss. They can be reached via 817-751-1513. You can verify their position with the company by their linkedin profile located at: https://www.linkedin.com/in/lisa-harmon-2991a53b."
                        }
                    }
                ]
            }

## DEPRECATED: Peer Review History [/api/v1/application/peer-review-history]

### Get Peer Review History [GET]

Get the list of what peers have reviewed already (identity, employment-claim, etc). 

+ Response 200
    + Body
    
            {
                "count": 1, 
                "next": null, 
                "previous": null, 
                "results": [
                    {
                        "id": 1,
                        "application_item": {
                            "id": 5,
                            "type": "identity",
                            "data": {
                                "proof_id": "82a65cae07098baf1bbc3010",
                                "proof_url": "https://twitter.com/joshuad31/status/715338474593714176",
                                "presentation_tag": "tweet",
                                "nametag": "joshuad31",
                                "human_url": "https://twitter.com/joshuad31/status/715338474593714176",
                                "state": 1,
                                "proof_type": "twitter",
                                "service_url": "https://twitter.com/joshuad31",
                                "sig_id": "4736793cfd5c53dc2991bd3d1e6c03f8228698aa5d83bb694e90cae358981aeb0f",
                                "presentation_group": "twitter"
                            }
                        },
                        "user": 6,
                        "data": "{\"policy_application\": {\"reason\": \"Good profile\", \"result\": 4, \"task_hash\": \"things\"}, \"public_key\": \"-----BEGIN PGP PUBLIC KEY BLOCK-----}"
                    }
                ]
            }


## DEPRECATED: Submit Peer Review [/api/v1/application/application-items/{applicationid}/submit-peer-review]

### Submit Peer Review [POST]

After the Peer has reviewed some parts of an application - he can set **Verify/Falsify/Can't Tell**. 

Please see [screenshot here](https://s4.postimg.org/47engihul/Screen_Shot_2016_08_17_at_19_05_14.png).

Please see [another screenshot here](https://s3.postimg.org/a501ucv83/Screen_Shot_2016_08_17_at_19_07_10.png).

That creates the message ```{"task_hash":"things","result":"no"}``` (for example) that he needs then to sign.


+ Parameters
    + applicationid (number) - ID of an an application

+ Request (application/json)
    + Body

            {
                "signed_message": "4234234jkfjsdlkfaj"
            }
        
+ Response 200