# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_address', models.CharField(max_length=1023)),
                ('to_address', models.CharField(max_length=1023)),
                ('hash', models.CharField(max_length=127, unique=True)),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('confirmations', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
