# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethtransaction',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
