# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ethaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillEthAccountOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ethaccount',
            name='immature_tokens_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ethaccount',
            name='mature_tokens_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fillethaccountoperation',
            name='eth_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_account_operation', to='payments.EthAccount'),
        ),
    ]
