# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_auto_20160929_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdeposit',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='smart_deposit', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
