# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_smartdeposit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdeposit',
            name='eth_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_deposits', to='payments.EthAccount'),
        ),
    ]
