# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_smartdeposit_coast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartdeposit',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='smartdeposit',
            name='amount_dollar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='smartdeposit',
            name='coast_dollar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='smartdeposit',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'init'), (1, 'submitted_wait_for_deposit'), (2, 'on_p2p_review')], default=0, protected=True),
        ),
        migrations.AddField(
            model_name='smartdeposit',
            name='wait_for',
            field=models.DateTimeField(null=True),
        ),
    ]
