# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20161007_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartdeposit',
            name='id',
        ),
        migrations.AlterField(
            model_name='smartdeposit',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='smart_deposit', serialize=False, to='policy.PolicyApplication'),
        ),
    ]
