# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 18:47
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_smartdeposit_exchange_rate_at_invoice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdeposit',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'init'), (1, 'wait_for_deposit'), (2, 'received')], default=0, protected=True),
        ),
    ]
