# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0020_auto_20161011_0847'),
        ('payments', '0012_auto_20161010_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeBetOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(null=True)),
                ('assessor_token_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_bet_operations', to='payments.TokenAccount')),
                ('internal_contractor_token_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_bet_operations', to='payments.TokenAccount')),
                ('risk_assessment_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='make_bet_operations', to='policy.RiskAssessmentTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
