# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_makebetoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethaccount',
            name='eth_node_host',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ethaccount',
            name='eth_address',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
