# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20161017_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdeposit',
            name='from_address',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
