# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_smartdeposit_from_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartdeposit',
            old_name='coast',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='smartdeposit',
            old_name='coast_dollar',
            new_name='cost_dollar',
        ),
    ]
