# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-22 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20161019_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartdeposit',
            name='tx_hash',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
