# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_smartdeposit_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdeposit',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
