# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20161024_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethaccount',
            name='eth_node_host',
        ),
        migrations.AddField(
            model_name='ethaccount',
            name='rpc_node_host',
            field=models.URLField(default='http://dynamisapp-develop.herokuapp.com:8545'),
        ),
    ]
