# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20161024_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethaccount',
            name='rpc_node_host',
            field=models.URLField(null=True),
        ),
    ]
