# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0020_auto_20161024_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buytokenoperation',
            name='eth_account',
        ),
        migrations.RemoveField(
            model_name='smartdeposit',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='smartdeposit',
            name='tx_hash',
        ),
        migrations.AddField(
            model_name='buytokenoperation',
            name='cost',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buytokenoperation',
            name='count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buytokenoperation',
            name='eth_tx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_token_operation', to='core.EthTransaction'),
        ),
        migrations.AddField(
            model_name='buytokenoperation',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'init'), (1, 'wait_for_tx'), (2, 'received')], default=0, protected=True),
        ),
        migrations.AddField(
            model_name='buytokenoperation',
            name='token_cost_at_invoice_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='buytokenoperation',
            name='wait_for',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='smartdeposit',
            name='eth_tx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_deposit', to='core.EthTransaction'),
        ),
        migrations.AlterField(
            model_name='buytokenoperation',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='smartdeposit',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'init'), (1, 'wait_for_tx'), (2, 'received')], default=0, protected=True),
        ),
    ]
