# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20161026_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytokenoperation',
            name='from_address',
            field=models.CharField(max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartdeposit',
            name='from_address',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
