# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-27 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20161027_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytokenoperation',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
