# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160428_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keybase_verified',
        ),
    ]
