# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_keybase_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keybase_username',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
