# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_risk_assessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_risk_assessor',
            field=models.BooleanField(default=False, help_text='Determines whether this user can participate as a risk assessor'),
        ),
    ]
