# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_account_configs(apps, schema_editor):
    AccountConfig = apps.get_model('accounts', 'AccountConfig')
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        AccountConfig.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160810_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rpc_node_host', models.URLField(default='http://localhost:8545')),
            ],
        ),
        migrations.RunPython(create_account_configs)
    ]
