# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_keybase_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
