# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_linkedin_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountConfig',
        ),
    ]
