# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160929_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='internal_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
