# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 07:34
from __future__ import unicode_literals

from django.db import migrations


def create_eth_accounts(apps, schema_editor):
    EthAccount = apps.get_model('payments', 'EthAccount')
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        EthAccount.objects.get_or_create(user=user)


def create_internal_contractor(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    if not User.objects.filter(internal_contractor=True).exists():
        User.objects.create(internal_contractor=True, email='internal_contractor@example.com')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_internal_contractor'),
        ('payments', '0004_auto_20160929_0040'),
    ]

    operations = [
        migrations.RunPython(create_internal_contractor),
        migrations.RunPython(create_eth_accounts)
    ]
